#!/usr/bin/env perl -w
#
# "xcodemake"
#
# Repo: https://github.com/johnno1962/xcodemake
#
# A short script to convert xcodebuild output into a Makefile.
# Once a Makefile has been generated you can use the much
# faster "make" command for most builds instead of launching
# the more ponderous xcodebuild for each iteration. Sure,
# this could be rewritten in python and use ninja instead.
#
# xcodebuild re-run if its arguments change or make fails or project modified.
# Makefile re-generated if script modified or xcodebuild recaptured.
#

use IO::File;
use Digest::MD5 qw(md5_hex);
use JSON::PP;
use strict;

my $dir = ".xcodemake";
mkdir $dir unless -d $dir;
my $make = "$dir/Makefile";

my $xcodebuild = ($ENV{DEVELOPER_BIN_DIR}||'/usr/bin')."/xcodebuild";
my $archs = $ENV{ARCHS}||'arm64';
my $hasConfiguration = grep { $_ eq "-config" || $_ eq "-configuration" } @ARGV;
my $hasScheme = grep { $_ eq "-scheme" } @ARGV;
push @ARGV, "-configuration", "Debug" if !$hasConfiguration && !$hasScheme;
my $args = join ' ', map { "'$_'" } @ARGV;

my $variant = "$xcodebuild ARCHS=$archs $args.";
my $logTag = join "_", @ARGV;
$logTag =~ s/[\/:]+/_/g;
$logTag =~ s/[^[:alnum:]._+=,@ -]+/_/g;
$logTag =~ s/\s+/_/g;
$logTag =~ s/_+/_/g;
$logTag =~ s/^_+|_+$//g;
$logTag ||= "default";
my $maxLogNameLength = 150;
my $logSuffix = "-" . md5_hex($variant) . ".log";
$logTag = substr($logTag, 0, $maxLogNameLength - length($logSuffix));
$logTag =~ s/_+$//;
my $log = "$dir/$logTag$logSuffix";
my $builddb = ($ENV{OBJROOT}||'/tmp')."/XCBuildData/build.db";
my $xcbuild = "/usr/bin/env -i '$xcodebuild' ARCHS=$archs $args";
my $EXIT_SUCCESS = 0;
my ($LOG, $fileArg);

# regex for file path argument
my $notSpace = "[^\\\\\\s]";
$fileArg = "$notSpace+(?:\\\\.$notSpace*)*";

sub escape {
    my ($chars) = @_;
    return unless defined $_[1];
    my $quoted = quotemeta $chars;
    $_[1] =~ s/([$quoted])/\\$1/g;
}

sub unescape {
    my ($chars) = @_;
    return unless defined $_[1];
    my $quoted = quotemeta $chars;
    $_[1] =~ s/\\([$quoted])/$1/g;
}

# escape $ for make
sub dollarEscape {
    return unless defined $_[0];
    $_[0] =~ s/\$/\$\$/g;
}

# escape file path for shell/make recipe use
sub shellEscape {
    escape "()", $_[0];
    dollarEscape $_[0];
}

# Extract values for the option from a command
sub extractOption {
    my ($line, $option) = @_;
    return unless defined $line;
    return my @a = $line =~ / $option ($fileArg)/g;
}

sub unescapePath {
    my ($path) = @_;
    return unless defined $path;
    $path =~ s/\\(.)/$1/g;
    return $path;
}

sub makeTargetPath {
    my ($path) = @_;
    $path = unescapePath($path);
    escape "\$& ", $path;
    return $path;
}

sub makeDependencyPath {
    my ($path) = @_;
    $path = unescapePath($path);
    escape " ", $path;
    dollarEscape $path;
    return $path;
}

sub shellPath {
    my ($path) = @_;
    $path = unescapePath($path);
    shellEscape $path;
    escape " ", $path;
    return $path;
}

sub nextLine {
    my $line = $LOG->getline() or return;
    chomp $line;
    return $line;
}

sub nextCD {
    my $line = nextLine() or return;
    my ($cd) = $line =~ /cd (.*)/;
    return unless defined $cd;
    unescape "^\$'()&", $cd;
    escape " ", $cd;
    dollarEscape $cd;
    return "\t\tcd $cd\n\t\t/usr/bin/time ";
}

# Recapture xcodebuild output if paramaters change or project has been edited
captureXcodebuild() if ! -f $log || `find . -name project.pbxproj -newer '$log'`;

# Regenerate Makefile (if script newer or different xcodebuild or arguments)
generateMakefile() if ! -f $make || -M $0 < -M $make || !makefileMatchesVariant();

exit $EXIT_SUCCESS if $EXIT_SUCCESS == system "make -f '$make'";

rename $builddb, $builddb.".save";

# If xcodebuild compiles, re-capture.
if ($EXIT_SUCCESS == system $xcbuild) {
    captureXcodebuild();
    generateMakefile();
    exit $EXIT_SUCCESS if $EXIT_SUCCESS == system "make -f '$make'";
}

rename $builddb.".save", $builddb;
exit !$EXIT_SUCCESS;

sub captureXcodebuild {
    # Move Xcode's build database to one side to
    # be able to use xcodebuild inside a scheme.
    rename $builddb, $builddb.".save";

    if (my ($bundle) = $variant =~ /-resultBundlePath ($fileArg)/) {
        $xcbuild = "rm -rf '$bundle'; $xcbuild";
    }
    my $command = "$xcbuild clean; $xcbuild 2>&1 | tee '$log'";
    warn "Executing: $command\n";
    if ($EXIT_SUCCESS != system $command) {
        unlink $log;
        exit !$EXIT_SUCCESS;
    }
    unlink $make;
    
    rename $builddb.".save", $builddb;
}

sub makefileMatchesVariant {
    my $MAKE = IO::File->new("< $make") or return;
    while (my $line = $MAKE->getline()) {
        return 1 if index($line, " $variant") >= 0;
    }
    return;
}

sub generateMakefile {
    $LOG = IO::File->new("< $log") or die "Could not open $log: $!";

    my $MAKE = IO::File->new("> $make") or die "Could not open $make: $!";
    print $MAKE <<HEADER;
#
# Generated @{[scalar localtime()]} from
# $variant
#

default: main

HEADER

    my (%rules, @linked, @codesigns);
    my $json = JSON::PP->new->utf8;
    my $printSwiftRule = sub {
        my ($object, $source, $command, $cd) = @_;
        return unless defined $object && defined $source && defined $command && defined $cd;

        my $target = makeTargetPath($object);
        return if $rules{$target}++;

        print $MAKE "\n$target: @{[makeDependencyPath($source)]}\n";
        print $MAKE "$cd$command && touch @{[shellPath($object)]}\n\n";
    };

    while (defined(my $line = nextLine())) {
        print $MAKE "# $line\n";
        # Add rules for "C" family sources.
        if (my ($object, $source) = $line =~
            /^CompileC ($fileArg) ($fileArg) /) {
            my $cd = nextCD();
            do {
                $line = nextLine();
            } while ($line =~ /^\s*$|response file/);
            unescape "{}()", $object;
            escape "\$&", $object;
            dollarEscape $source;
            unescape "'", $source;
            print $MAKE "\n$object: $source\n";
            shellEscape $object;
            dollarEscape $line;
            print $MAKE "$cd$line && touch $object\n\n";
        # Add rules for SwiftDriver output (Xcode 16.3+).
        } elsif ($line =~ /^SwiftDriver .* com\.apple\.xcode\.tools\.swift\.compiler/) {
            my $cd = nextCD();
            my $driver = nextLine();
            next unless defined $driver;
            next unless $driver =~ s/^\s*builtin-SwiftDriver\s+--\s+//;
            $driver =~ s/\s+-use-frontend-parseable-output//;

            my ($outputMap) = $driver =~ / -output-file-map ($fileArg)/;
            unless (defined $outputMap) {
                warn "Could not find SwiftDriver -output-file-map: $driver\n";
                next;
            }
            $outputMap = unescapePath($outputMap);

            my $MAP = IO::File->new("< $outputMap");
            unless ($MAP) {
                warn "Could not open SwiftDriver output file map $outputMap: $!\n";
                next;
            }
            my $mapContent = do { local $/; <$MAP> };
            close $MAP;

            my $outputFiles = eval { $json->decode($mapContent) };
            if ($@ || ref $outputFiles ne "HASH") {
                warn "Could not parse SwiftDriver output file map $outputMap: $@\n";
                next;
            }

            dollarEscape $driver;
            # macOS ships GNU Make 3.81, which does not support grouped targets.
            for my $source (sort keys %$outputFiles) {
                next unless $source =~ /\.swift$/;
                next unless ref $outputFiles->{$source} eq "HASH";
                $printSwiftRule->($outputFiles->{$source}->{object}, $source, $driver, $cd);
            }
        # Add rules for Swift sources (expand batches)
        } elsif ($line =~ /^SwiftCompile \w+ \w+/) {
            my $cd = nextCD();
            next unless defined $cd;
            $line = nextLine();
            next unless defined $line;
            next unless $line =~ /builtin-swiftTaskExecution|swift-frontend/;
            $line =~ s/builtin-swiftTaskExecution -- |-frontend-parseable-output//g;
            my @sources = extractOption($line, "-primary-file")
                or next;
            my @objects = extractOption($line, "-o");
            # print "# $line\n@sources -- @objects\n\n";
            dollarEscape $line;
            foreach my $i (0..$#sources) {
                $printSwiftRule->($objects[$i], $sources[$i], $line, $cd);
            }
        # Add rule to link executables
        } elsif (my ($executable) = $line =~ /^Ld ($fileArg) /) {
            my $cd = nextCD();
            $line = nextLine();
            my ($linkfile) = extractOption($line, "-filelist") or next;
            $linkfile = unescapePath($linkfile);
            print("Link file for $executable: $linkfile\n");
            my $OBJS = IO::File->new("< $linkfile") || IO::File->new("< /dev/null");
            escape "&\$", $executable;
            print $MAKE "\n$executable:";
            while (my $object = $OBJS->getline()) {
                chomp $object;
                escape " '&\$", $object;
                next if $object eq $executable || !$rules{$object};
                print $MAKE " $object";
            }
            dollarEscape $line;
            print $MAKE "\n$cd$line\n\n";
            push @linked, $executable if $executable !~ /\.o$/;
        } elsif ($line =~ m@^    /usr/bin/(codesign|touch)@) {
            dollarEscape $line;
            push @codesigns, $line;
        }
    }

    print $MAKE "main: @linked\n";
    print $MAKE join "\n", map {"\t$_"} @codesigns;
    print $MAKE "\n";
    close $MAKE;
}
